### ISSUE TITLE
{ support_status: 'Unsupported' }

### ISSUE THREAD

**Issue by dsmddsmd** [Web3BotHub/gradient-bot#1]
![Screenshot_575](https://github.com/user-attachments/assets/aa42a46a-28dd-41c9-92c8-ca54c9e6e958)
![Screenshot_576](https://github.com/user-attachments/assets/354e7946-ccdf-45a1-af60-f6b1839f323e)

**Comment by overtrue** [comment]
这种就是代理 ip 的问题了哈
