### ISSUE TITLE
TimeoutError: Waiting for element to be located By(xpath, //*[contains(text(), "Copy Referral Link")])

### ISSUE THREAD

**Issue by mainframer** [web3bothub/gradient-bot#10]
|gradient-3  | -> Getting proxy IP info: socks5h://twoan_4-country-us:BM2KZ9@proxysg.socks5.io:3003
2|gradient-2  | -> Proxy IP info: 当前 IP：71.121.184.163  来自于：美国 马里兰州 雷斯特斯敦  verizon.com
2|gradient-2  | -> Started! Logging in https://app.gradient.network/...
3|gradient-3  | -> Proxy IP info: 当前 IP：173.24.67.32  来自于：美国 威斯康星州 莫斯顿  mediacomcable.com
3|gradient-3  | -> Started! Logging in https://app.gradient.network/...
4|gradient-4  | -> Proxy IP info: 当前 IP：38.210.52.154  来自于：巴西 巴西
4|gradient-4  | -> Started! Logging in https://app.gradient.network/...
0|gradient-0  | Error occurred: TimeoutError: Waiting for element to be located By(xpath, //*[contains(text(), "Copy Referral Link")])
0|gradient-0  | Wait timed out after 30238ms
0|gradient-0  |     at /app/node_modules/selenium-webdriver/lib/webdriver.js:923:22
0|gradient-0  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
0|gradient-0  |   remoteStacktrace: ''
0|gradient-0  | }
0|gradient-0  | TimeoutError: Waiting for element to be located By(xpath, //*[contains(text(), "Copy Referral Link")])
0|gradient-0  | Wait timed out after 30238ms
0|gradient-0  |     at /app/node_modules/selenium-webdriver/lib/webdriver.js:923:22
0|gradient-0  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2|gradient-2  | Error occurred: TimeoutError: Waiting for element to be located By(xpath, //*[contains(text(), "Copy Referral Link")])
2|gradient-2  | Wait timed out after 30058ms
2|gradient-2  |     at /app/node_modules/selenium-webdriver/lib/webdriver.js:923:22
2|gradient-2  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
2|gradient-2  |   remoteStacktrace: ''
2|gradient-2  | }
2|gradient-2  | TimeoutError: Waiting for element to be located By(xpath, //*[contains(text(), "Copy Referral Link")])
2|gradient-2  | Wait timed out after 30058ms
2|gradient-2  |     at /app/node_modules/selenium-webdriver/lib/webdriver.js:923:22
2|gradient-2  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
PM2           | App [gradient-0:0] exited with code [1] via signal [SIGINT]
PM2           | App [gradient-0:0] starting in -fork mode-
PM2           | App [gradient-0:0] online
PM2           | App [gradient-2:2] exited with code [1] via signal [SIGINT]
PM2           | App [gradient-2:2] starting in -fork mode-
PM2           | App [gradient-2:2] online

**Comment by overtrue** [comment]
`docker pull overtrue/gradient-bot ` and delete the old pod, restart a new pod
