### ISSUE TITLE
WebDriverError: chrome not reachable

### ISSUE THREAD

**Issue by luqmanfajar** [web3bothub/gradient-bot#16]
when run on docker goes like this 
WebDriverError: chrome not reachable
8|gradient-8  |     at Object.throwDecodedError (/app/node_modules/selenium-webdriver/lib/error.js:521:15)
8|gradient-8  |     at parseHttpResponse (/app/node_modules/selenium-webdriver/lib/http.js:514:13)
8|gradient-8  |     at Executor.execute (/app/node_modules/selenium-webdriver/lib/http.js:446:28)
8|gradient-8  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by overtrue** [comment]
please confirm your proxy is working: 

```
curl -vv -x socks5://xxxx:xxxx@ip:port https://myip.ipip.net
```

**Comment by overtrue** [comment]
and please check your server status:

```bash
top
```

Check how much memory is left, because you can't run too many proxy IPs on one machine.

**Comment by overtrue** [comment]
delete pod and restart
