### ISSUE TITLE
use proxy http

### ISSUE THREAD

**Issue by maianhbao1** [web3bothub/gradient-bot#18]
I have filled in proxy http://user:pass@ip:port in proxies.txt but the account still only runs without proxy? How to fix that?
![Screenshot 2024-11-04 131407](https://github.com/user-attachments/assets/c287e671-f762-4df5-82b4-e1e81c7a235c)

**Comment by overtrue** [comment]
no docker?

**Comment by maianhbao1** [comment]
> không có docker?

run bot using docker

**Comment by overtrue** [comment]
paste your docker run command.

**Comment by maianhbao1** [comment]
> paste your docker run command.

It's a pity that I'm not familiar with using Docker

**Comment by overtrue** [comment]
how  did you run the pod ?
