### ISSUE TITLE
Error occurred: TimeoutError: Waiting for element to be located By(xpath, //*[contains(text(), "Today's Taps")])

### ISSUE THREAD

**Issue by sitxxar** [web3bothub/gradient-bot#19]
![image](https://github.com/user-attachments/assets/1efa89e8-23d6-4ba5-bb92-1f6bba7ddabf)

**Comment by Repopribadi27** [comment]
Same error

**Comment by sitxxar** [comment]
> Same error

still got error ?

**Comment by dn9568** [comment]
same error

**Comment by overtrue** [comment]
docker pull overtrue/gradient-bot and remove old pod, and re-run.
