### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by xHocusPocusx** [web3bothub/gradient-bot#2]
Tried the docker version on two different server os. CPU usage hits 100% as soon as the script starts working.

**Comment by overtrue** [comment]
because it's based on headless chrome.

**Comment by xHocusPocusx** [comment]
@overtrue so is there any way to reduce the cpu load?

**Comment by overtrue** [comment]
> so is there any way to reduce the cpu load?

This mode itself is relatively resource-consuming. However, I cannot reproduce the 100% situation you mentioned. In the case of one account and one proxy, the resource usage is less than 10%.

**Comment by xHocusPocusx** [comment]
> > so is there any way to reduce the cpu load?
> 
> This mode itself is relatively resource-consuming. However, I cannot reproduce the 100% situation you mentioned. In the case of one account and one proxy, the resource usage is less than 10%.

I have tried with one account and one proxy. CPU hits 100% all 4 cores I have, as soon as the script launches. 

```
0|gradient-0  | -> Started! Logging in https://app.gradient.network/...
0|gradient-0  | -> Logged in! Waiting for open extension...
0|gradient-0  | -> Extension loaded!
0|gradient-0  | -> "I got it" button clicked!
0|gradient-0  | -> Gradient is available in your region. 
0|gradient-0  | -> Status: Good
0|gradient-0  | -> Connected! Starting rolling...
0|gradient-0  | { support_status: 'Good' }
0|gradient-0  | -> Lunched!
```

**Comment by MrTimonM** [comment]
same, I cant run like this
