### ISSUE TITLE
Error: Unable to obtain browser driver.

### ISSUE THREAD

**Issue by luqmanfajar** [web3bothub/gradient-bot#20]

**Comment by luqmanfajar** [comment]
<img width="1272" alt="image" src="https://github.com/user-attachments/assets/266921c0-e731-4a88-95a1-3e4220caed07">

**Comment by dn9568** [comment]
same

**Comment by overtrue** [comment]
did you pulled the latest docker image?

```
docker pull overtrue/gradient-bot
```

**Comment by dn9568** [comment]
> did you pulled the latest docker image?
> 
> ```
> docker pull overtrue/gradient-bot
> ```

yes i pull 1 hr ago will error

**Comment by overtrue** [comment]
how many lines in your proxies.txt?

**Comment by dn9568** [comment]
> how many lines in your proxies.txt?

7 proxies

**Comment by overtrue** [comment]
Try changing it to 3 lines, and to see the current memory usage of the server, use the command `top` and paste the top 4 lines here

**Comment by overtrue** [comment]
https://t.me/+XPImYd6qchU3NTE1

**Comment by dn9568** [comment]
now i try use 4 proxie

**Comment by luqmanfajar** [comment]
i just using 1 proxy

**Comment by overtrue** [comment]
1. list the running containers  by: `docker ps`
2. remove old containers by: `docker rm -f <containerid>`
3. pull the latest image: `docker pull overtrue/gradient-bot`
4. restart the container.
