### ISSUE TITLE
Pls update for ARM64 version

### ISSUE THREAD

**Issue by bscongluanbui** [web3bothub/gradient-bot#23]
Can you update this for ARM64 version on the future?

**Comment by overtrue** [comment]
https://hub.docker.com/repository/docker/overtrue/gradient-bot/tags

**Comment by bscongluanbui** [comment]
> https://hub.docker.com/repository/docker/overtrue/gradient-bot/tags

HI I just pull the docker for arm and got error with 
"Error occurred: Error: Unable to obtain browser driver"
 For more information on how to install drivers see

2|gradient-2  |         https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location/. Error: Error executing command for /app/node_modules/selenium-webdriver/bin/linux/selenium-manager with --browser,chrome,--language-binding,javascript,--output,json,--proxy,http://127.0.0.1:40685: /app/node_modules/selenium-webdriver/bin/linux/selenium-manager: 1: Syntax error: "(" unexpected

2|gradient-2  |     at getBinaryPaths (/app/node_modules/selenium-webdriver/common/driverFinder.js:38:11)

2|gradient-2  |     at thenableWebDriverProxy.createSession (/app/node_modules/selenium-webdriver/chromium.js:627:45)

2|gradient-2  |     at thenableWebDriverProxy.createSession (/app/node_modules/selenium-webdriver/chrome.js:219:42)

2|gradient-2  |     at createDriver (/app/node_modules/selenium-webdriver/index.js:153:33)

2|gradient-2  |     at Builder.build (/app/node_modules/selenium-webdriver/index.js:674:16)

2|gradient-2  |     at /app/app.js:207:8

2|gradient-2  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
