### ISSUE TITLE
Error: Constantly disconnecting

### ISSUE THREAD

**Issue by Lukey372** [web3bothub/gradient-bot#27]
Having issues where my proxies are constantly disconnecting upon launch.
Proxies are stable and are paid however unsure why this is occuring.

![image](https://github.com/user-attachments/assets/70cf06f2-59e2-4d9c-8d9c-43fa747fe7a1)

**Comment by overtrue** [comment]
> Having issues where my proxies are constantly disconnecting upon launch.
> 
> Proxies are stable and are paid however unsure why this is occuring.
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/70cf06f2-59e2-4d9c-8d9c-43fa747fe7a1)

It is not the case that if the IP is fine, it can definitely be used. This status depends on the determination of the official, not this robot.

**Comment by Lukey372** [comment]
Sorry what do you mean by "This status depends on the determination of the official"

I have tried about 5-6 IPs and I am having the same issue where it constantly disconnects and then it goes back through the disconnect and reconnect again.

**Comment by overtrue** [comment]
> Sorry what do you mean by "This status depends on the determination of the official"
> 
> 
> 
> I have tried about 5-6 IPs and I am having the same issue where it constantly disconnects and then it goes back through the disconnect and reconnect again.

The Gradient official will determine the source of the IP, the quality of the link, and finally decide to display good, disconnected or unsupported. If you can see this status, it indicates that the robot is working properly, because this status text is retrieved from the page of the browser extension.

**Comment by overtrue** [comment]
At present, the purchased IP must be a static residential IP. The one I purchased has accumulated more than 10,000 points and has always been good.

**Comment by Lukey372** [comment]
> At present, the purchased IP must be a static residential IP. The one I purchased has accumulated more than 10,000 points and has always been good.

Understand that, I have tried a proxy from proxy-seller as well as proxiware, both are static resi and I am getting the same issue. I'll try and reinstall and hopefully resolve it.

**Comment by Lukey372** [comment]
Reinstall fixed it + pull of overtrue/gradient thanks alot
