### ISSUE TITLE
HOW TO USE WITH PROXY?

### ISSUE THREAD

**Issue by dimasdamargalih** [web3bothub/gradient-bot#36]
I just added 1 proxy in the folder proxies.txt:/app/proxies.txt
when I run the docker, it say running without the proxy. why?

**Comment by Anhairdrop** [comment]
![Screenshot 2024-11-16 203439](https://github.com/user-attachments/assets/a1243cc2-8d9f-4336-ac8c-ce033915eaee)
NOT supported when running multiple proxies on docker

**Comment by overtrue** [comment]
> ![Screenshot 2024-11-16 203439](https://private-user-images.githubusercontent.com/73512523/386848698-a1243cc2-8d9f-4336-ac8c-ce033915eaee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE3NjUyMzEsIm5iZiI6MTczMTc2NDkzMSwicGF0aCI6Ii83MzUxMjUyMy8zODY4NDg2OTgtYTEyNDNjYzItOGQ5Zi00MzM2LWFjOGMtY2UwMzM5MTVlYWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE2VDEzNDg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNmUwN2YxNWNkZGM2NjcwNTE4MjA1ZGIzN2UzZDdmZWQ5NmE1MTMzMWU1YTI2NThkZmJiOTY2ODkyMWUzMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r46LWjSk-VoP7JwR5qa8HmMm_zqr-KKr-QwuPHzv7FY) NOT supported when running multiple proxies on docker

This indicates that your proxy is not recognized by the official. So far, only static residential IPs have proven to be effective during the trial. If you can see "Launched", it means that the Bot has been successfully run. Check the type and quality of your proxy.
