### ISSUE TITLE
Unsupported

### ISSUE THREAD

**Issue by Anhairdrop** [web3bothub/gradient-bot#37]
![Screenshot 2024-11-17 195001](https://github.com/user-attachments/assets/9882d58a-04a9-4515-9103-c6b64a50bb0d)
getting unsupported error when running on docker

**Comment by overtrue** [comment]
If you see "Good", it proves that the script has been successful. As for why there is no credit, you'll have to ask the official. After all, the script only helps you connect to the network. If you don't see "Good", then there may be problems with the script or the proxy IP. The official also has breakdowns frequently.
