### ISSUE TITLE
how set multi proxy 

### ISSUE THREAD

**Issue by dsmddsmd** [Web3BotHub/gradient-bot#4]
how set multi proxy

**Comment by overtrue** [comment]
multi line

**Comment by dsmddsmd** [comment]
![image](https://github.com/user-attachments/assets/9a264e40-4bfc-41e3-88f3-821cd0ff45ea)
true?

**Comment by overtrue** [comment]
> ![image](https://github.com/user-attachments/assets/9a264e40-4bfc-41e3-88f3-821cd0ff45ea)
> 
> true?

yes
