### ISSUE TITLE
I can see the status good in the log,but can't see the node info in the dashboard

### ISSUE THREAD

**Issue by linflg** [web3bothub/gradient-bot#47]

**Comment by linflg** [comment]
![image](https://github.com/user-attachments/assets/7823f1fe-98e4-444e-b5fb-d92debc60933)

**Comment by overtrue** [comment]
If you see "Good", then the work of this script has been completed and other things have nothing to do with the bot. Moreover, even if you see "Good", the status won't be visible on the official website immediately. There is a certain delay. If you still can't see it, you can only ask the official. Of course, the official surely won't accept your execution in this way.
