### ISSUE TITLE
TimeoutError

### ISSUE THREAD

**Issue by monstertrakk** [web3bothub/gradient-bot#5]
0|gradient-0  | Error occurred: TimeoutError: Waiting for element to be located By(css selector, [placeholder="Enter Email"])
0|gradient-0  | Wait timed out after 30071ms
0|gradient-0  |     at /app/node_modules/selenium-webdriver/lib/webdriver.js:923:22
0|gradient-0  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
0|gradient-0  |   remoteStacktrace: ''
0|gradient-0  | }
0|gradient-0  | TimeoutError: Waiting for element to be located By(css selector, [placeholder="Enter Email"])
0|gradient-0  | Wait timed out after 30071ms
0|gradient-0  |     at /app/node_modules/selenium-webdriver/lib/webdriver.js:923:22
0|gradient-0  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
PM2           | App [gradient-0:0] exited with code [1] via signal [SIGINT]
PM2           | App [gradient-0:0] starting in -fork mode-
PM2           | App [gradient-0:0] online

**Comment by overtrue** [comment]
validate your proxy ip to ensure it works

**Comment by monstertrakk** [comment]
> validate your proxy ip to ensure it works

what providers can you recommend?

**Comment by overtrue** [comment]
> > validate your proxy ip to ensure it works
> 
> 
> 
> what providers can you recommend?

https://app.proxy-cheap.com/r/ksvW8Z
